services:
  mkdocs:
    build: .
    container_name: portfolio-mkdocs

    ports:
      - "127.0.0.1:8085:8000"

    volumes:
      - .:/app
      - ./site:/usr/share/nginx/html:ro

    restart: unless-stopped